//go:build !extlib
// +build !extlib

package x264c

/*
#cgo android LDFLAGS: -lm
#cgo windows LDFLAGS:
#cgo linux,!android LDFLAGS: -lpthread -lm
#cgo darwin LDFLAGS: -lpthread -lm

#cgo linux,386 CFLAGS: -DSYS_LINUX=1 -DARCH_X86=1 -DHAVE_POSIXTHREAD=1 -DSTACK_ALIGNMENT=64 -DHAVE_MALLOC_H=1 -DHAVE_CPU_COUNT=1 -DTHP=1
#cgo linux,amd64 CFLAGS: -DSYS_LINUX=1 -DARCH_X86_64=1 -DHAVE_POSIXTHREAD=1 -DSTACK_ALIGNMENT=64 -DHAVE_MALLOC_H=1 -DHAVE_CPU_COUNT=1 -DTHP=1
#cgo linux,!android,arm CFLAGS: -DSYS_LINUX=1 -DARCH_ARM=1 -DHAVE_POSIXTHREAD=1 -DSTACK_ALIGNMENT=4 -DHAVE_MALLOC_H=1 -DHAVE_CPU_COUNT=1 -DTHP=1
#cgo linux,!android,arm64 CFLAGS: -DSYS_LINUX=1 -DARCH_AARCH64=0 -DHAVE_POSIXTHREAD=1 -DSTACK_ALIGNMENT=16 -DHAVE_MALLOC_H=1 -DHAVE_CPU_COUNT=1 -DTHP=1
#cgo windows,386 CFLAGS: -DSYS_WINDOWS=1 -DARCH_X86=1 -DHAVE_WIN32THREAD=1 -DSTACK_ALIGNMENT=64 -DHAVE_MALLOC_H=0 -DHAVE_CPU_COUNT=0 -DTHP=0
#cgo windows,amd64 CFLAGS: -DSYS_WINDOWS=1 -DARCH_X86_64=1 -DHAVE_WIN32THREAD=1 -DSTACK_ALIGNMENT=16 -DHAVE_MALLOC_H=0 -DHAVE_CPU_COUNT=0 -DTHP=0
#cgo darwin,amd64 CFLAGS: -DSYS_MACOSX=1 -DARCH_X86_64=1 -DHAVE_POSIXTHREAD=1 -DSTACK_ALIGNMENT=16 -DHAVE_MALLOC_H=0 -DHAVE_CPU_COUNT=0 -DTHP=1
#cgo android,arm CFLAGS: -DSYS_LINUX=1 -DARCH_ARM=1 -DHAVE_THREAD=1 -DHAVE_POSIXTHREAD=1 -DSTACK_ALIGNMENT=4 -DHAVE_MALLOC_H=1 -DHAVE_CPU_COUNT=0 -DTHP=1
#cgo android,arm64 CFLAGS: -DSYS_LINUX=1 -DARCH_AARCH64=1 -DHAVE_THREAD=1 -DHAVE_POSIXTHREAD=1 -DSTACK_ALIGNMENT=16 -DHAVE_MALLOC_H=1 -DHAVE_CPU_COUNT=1 -DTHP=1

#cgo CFLAGS: -std=gnu99 -Iexternal/x264 -D_GNU_SOURCE -fomit-frame-pointer -Wshadow -O3
#cgo CFLAGS: -DHAVE_THREAD=1 -DHAVE_LOG2F=1 -DHAVE_STRTOK_R=1 -DHAVE_MMAP=1 -DHAVE_GPL=1 -DHAVE_INTERLACED=1
#cgo CFLAGS: -DHAVE_SWSCALE=0 -DHAVE_LAVF=0 -DHAVE_AVS=0 -DUSE_AVXSYNTH=0 -DHAVE_VECTOREXT=1 -DHAVE_BITDEPTH8=1 -DHAVE_BITDEPTH10=0
#cgo CFLAGS: -DHIGH_BIT_DEPTH=0 -DHAVE_OPENCL=0 -DHAVE_ALTIVEC=0 -DHAVE_ALTIVEC_H=0 -DHAVE_FFMS=0 -DHAVE_GPAC=0 -DHAVE_LSMASH=0
#cgo CFLAGS: -DBIT_DEPTH=8 -DX264_BIT_DEPTH=8 -DX264_GPL=1 -DX264_INTERLACED=1 -DX264_CHROMA_FORMAT=0
*/
import "C"
